// import appTests from './app';
// import createArticleTests from './articles/create';
// import deleteArticleTests from './articles/delete';
// import getArticleTests from './articles/get';
// import updateArticleTests from './articles/update';
// import createCommentTests from './comments/create';
// import deleteCommentTests from './comments/delete';
// import adminTests from './users/admin';
// import loginTests from './users/login';
// import signupTests from './users/signup';

// // appTests();
// signupTests();
// loginTests();
// adminTests();
// createArticleTests();
// getArticleTests();
// updateArticleTests();
// deleteArticleTests();
// createCommentTests();
// deleteCommentTests();
